title: My Professional Site
description: Portfolio and Projects by Ashwani
remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag

comments:
  provider: disqus
  disqus:
    shortname: your-disqus-shortname

google_analytics: UA-XXXXXXXXX-X
